const coreSubjectTests = [
    {
        title: "Database Management Systems (DBMS)",
        description: "Assessment on transaction properties (ACID), index mechanics, normal forms, and relational data architecture.",
        category: "dbms",
        difficulty: "general",
        duration: 20,
        questions: [
            // Easy (7 Questions)
            { questionText: "What does the 'A' in ACID properties of a database transaction stand for?", options: ["Atomicity", "Association", "Availability", "Aggregability"], correctOptionIndex: 0, difficulty: "easy", explanation: "Atomicity ensures that all operations within a transaction are completed successfully; otherwise, the transaction is aborted." },
            { questionText: "Which normal form deals with removing multi-valued dependencies?", options: ["1NF", "2NF", "3NF", "4NF"], correctOptionIndex: 3, difficulty: "easy", explanation: "Fourth Normal Form (4NF) requires that there are no non-trivial multi-valued dependencies in the schema." },
            { questionText: "Which SQL clause is used to filter records after aggregation?", options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"], correctOptionIndex: 1, difficulty: "easy", explanation: "The HAVING clause is used to filter records after group operations, whereas WHERE filters before." },
            { questionText: "What represents a link between database tables?", options: ["Primary Key", "Foreign Key", "Unique Key", "Super Key"], correctOptionIndex: 1, difficulty: "easy", explanation: "A Foreign Key is a field in one table that uniquely identifies a row of another table." },
            { questionText: "Which database type uses schemas and tables?", options: ["NoSQL DB", "Relational DB", "Graph DB", "Key-Value store"], correctOptionIndex: 1, difficulty: "easy", explanation: "Relational DBMS databases store values in highly structured tables and columns." },
            { questionText: "What is the default port number of standard MySQL Databases?", options: ["5432", "27017", "3306", "8080"], correctOptionIndex: 2, difficulty: "easy", explanation: "MySQL services run on port 3306 by default." },
            { questionText: "What operation retrieves matching values from multiple tables?", options: ["JOIN", "UNION", "MERGE", "INTERSECT"], correctOptionIndex: 0, difficulty: "easy", explanation: "JOIN retrieves combining records from two or more tables based on a related join condition." },

            // Medium (7 Questions)
            { questionText: "What type of locking is used to solve the dirty read problem?", options: ["Shared Lock", "Exclusive Lock", "Intent Lock", "Two-Phase locking"], correctOptionIndex: 1, difficulty: "medium", explanation: "An exclusive lock prevents another transaction from reading or writing data." },
            { questionText: "Which normal form requires the relation to be in 2NF and have no transitive functional dependencies?", options: ["1NF", "3NF", "BCNF", "4NF"], correctOptionIndex: 1, difficulty: "medium", explanation: "A relation is in 3NF if it is in 2NF and has no transitive dependencies." },
            { questionText: "What index type is built on a column whose values do not have a natural sorted file ordering?", options: ["Clustered Index", "Non-Clustered Index", "Primary Index", "Secondary Index"], correctOptionIndex: 1, difficulty: "medium", explanation: "Non-clustered indexes contain pointer indexes to storage records without changing the physical ordering." },
            { questionText: "In Two-Phase Locking (2PL), what describes the growing phase?", options: ["Locks can be acquired but not released", "Locks can be released but not acquired", "Locks are held until commit time", "No locks are acquired"], correctOptionIndex: 0, difficulty: "medium", explanation: "During growing phase, transactions acquire locks but cannot release any." },
            { questionText: "What is BCNF?", options: ["Strict version of 2NF", "Strict version of 3NF", "Normal form based on multi-valued dependencies", "A form that allows transitive dependencies"], correctOptionIndex: 1, difficulty: "medium", explanation: "Boyce-Codd Normal Form is a stricter and cleaner version of Third Normal Form." },
            { questionText: "What does database physical data independence ensure?", options: ["Logical schema changes do not affect queries", "Physical storage configuration changes do not affect logical schemas", "Database can be run on any hardware", "Concurrent transactions run in isolation"], correctOptionIndex: 1, difficulty: "medium", explanation: "Physical data independence enables altering physical formats (indexes, paths) without rewriting logical queries." },
            { questionText: "Which database system utilizes Graph database models?", options: ["Redis", "Cassandra", "Neo4j", "PostgreSQL"], correctOptionIndex: 2, difficulty: "medium", explanation: "Neo4j is a popular native graph database system." },

            // Hard (6 Questions)
            { questionText: "Which transaction isolation level avoids non-repeatable reads but allows phantom reads?", options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"], correctOptionIndex: 2, difficulty: "hard", explanation: "Repeatable Read locks values read but doesn't lock tables, so phantom insert insertions can still occur." },
            { questionText: "What guarantees strict database schedule order without cascading rollbacks?", options: ["Strict 2PL", "Rigorous 2PL", "Basic 2PL", "Conservative 2PL"], correctOptionIndex: 0, difficulty: "hard", explanation: "Strict 2PL releases exclusive locks only after commit, preventing cascading rollbacks." },
            { questionText: "If attribute set A determines B, and B determines C, what normal form criteria is most directly violated if A is not a candidate key?", options: ["2NF", "3NF", "4NF", "5NF"], correctOptionIndex: 1, difficulty: "hard", explanation: "This transitive dependency (A -> B -> C) directly violates 3NF rules." },
            { questionText: "What is an index organized table (IOT) structure?", options: ["Table is stored as a B+ tree index sorted by primary key", "Table contains heap files and index arrays", "Index is stored in primary partitions", "No physical keys are stored"], correctOptionIndex: 0, difficulty: "hard", explanation: "Index Organized Tables store user data directly on leaf nodes of primary B+ key indexes." },
            { questionText: "What specifies serializability order based on Timestamp Ordering protocols?", options: ["Read-timestamp of transactions", "Write-timestamp of transactions", "Unique start timestamp assigned to transaction", "Arrival order at DBMS server"], correctOptionIndex: 2, difficulty: "hard", explanation: "Ordering runs strictly based dynamically on start timestamps (TS(T)) assigned to active transactions." },
            { questionText: "What describes the CAP Theorem trade-off in Nosql databases?", options: ["Consistency, Availability, Partition Tolerance", "Complexity, Availability, Performance", "Concurrency, Accessibility, Persistence", "Control, Authentication, Privacy"], correctOptionIndex: 0, difficulty: "hard", explanation: "The CAP theorem states a distributed network database can satisfy at most two out of three criteria: Consistency, Availability, and Partition Tolerance." }
        ]
    },
    {
        title: "Operating Systems (OS)",
        description: "Assessment on processes scheduling algorithms, deadlock handling mechanisms, memory paging, and file management threads.",
        category: "os",
        difficulty: "general",
        duration: 20,
        questions: [
            // Easy (7 Questions)
            { questionText: "What component loads system boot files from disk to RAM on startup?", options: ["Assembler", "Linker", "Bootstrap loader", "Compiler"], correctOptionIndex: 2, difficulty: "easy", explanation: "The bootstrap loader retrieves and starts the OS kernel from secondary storage." },
            { questionText: "Which scheduler chooses processes from disk pool and loads them to main memory?", options: ["Short-term scheduler", "Medium-term scheduler", "Long-term scheduler", "Dispatcher"], correctOptionIndex: 2, difficulty: "easy", explanation: "The Long-term Scheduler (or job scheduler) controls process density by loading processes from disk buffer pools." },
            { questionText: "What state is a process in while waiting for CPU execution turns?", options: ["New state", "Ready state", "Running state", "Terminated state"], correctOptionIndex: 1, difficulty: "easy", explanation: "A process waiting in RAM for a CPU assignment is placed in the Ready state." },
            { questionText: "What condition is it when two processes wait infinitely for each other to release system resources?", options: ["Deadlock", "Starvation", "Context Switch", "Interrupt"], correctOptionIndex: 0, difficulty: "easy", explanation: "Deadlock is a blockage state where multiple threads wait for resources held locked by other processes." },
            { questionText: "What does virtual memory paging divide main memory into?", options: ["Pages", "Blocks", "Frames", "Segments"], correctOptionIndex: 2, difficulty: "easy", explanation: "Memory paging splits physical main memory into fixed-size chunks called frames." },
            { questionText: "Which command in linux lists active process metrics?", options: ["ls", "grep", "top", "chmod"], correctOptionIndex: 2, difficulty: "easy", explanation: "The 'top' tool displays dynamic, real-time metrics showing processor activities and threads." },
            { questionText: "What system call is used to create a new child process in UNIX?", options: ["fork()", "exec()", "signal()", "wait()"], correctOptionIndex: 0, difficulty: "easy", explanation: "The fork() system call creates a duplicate child process that inherits properties from the parent." },

            // Medium (7 Questions)
            { questionText: "What CPU scheduling algorithm can lead to starvation for long processes?", options: ["Round Robin", "Shortest Job Next (SJN)", "First Come First Served (FCFS)", "Multi-level Queue Scheduling"], correctOptionIndex: 1, difficulty: "medium", explanation: "Shortest Job Next continuously schedules short processes, starving longer jobs if short jobs arrive continually." },
            { questionText: "Which page replacement algorithm replaces the page that has not been used for the longest time?", options: ["First In First Out (FIFO)", "Optimal Page Replacement", "Least Recently Used (LRU)", "Least Frequently Used (LFU)"], correctOptionIndex: 2, difficulty: "medium", explanation: "Least Recently Used (LRU) tracking keeps usage histories and expels pages idle for the longest duration." },
            { questionText: "What is Belady's Anomaly?", options: ["Page faults decrease on increasing page frames", "Page faults increase on increasing page frames in FIFO", "Memory speed decreases as context swaps increase", "Starvation occurs in priority scheduling"], correctOptionIndex: 1, difficulty: "medium", explanation: "Belady's anomaly shows that in FIFO systems, adding page frames can sometimes increase page fault counts." },
            { questionText: "What technique is used to avoid deadlocks by verifying unsafe resource allocations?", options: ["Banker's Algorithm", "Mutual Exclusion", "Resource Preemption", "Detection and Recovery"], correctOptionIndex: 0, difficulty: "medium", explanation: "Banker's Algorithm calculates safe/unsafe allocation checks to prevent deadlock occurrence." },
            { questionText: "What is thrashing in operating programming?", options: ["Cleaning up deleted files from storage", "Operating system spends more time reading pages in/out than executing processes", "High process execution speed", "Thread context switching optimization"], correctOptionIndex: 1, difficulty: "medium", explanation: "Thrashing occurs when total pages allocated are insufficient for active processes, causing constant page swaps." },
            { questionText: "What memory mapping system divides memory space based on logical program parts (e.g. functions, variables)?", options: ["Paging", "Segmentation", "Dynamic Partitioning", "Fragmentation"], correctOptionIndex: 1, difficulty: "medium", explanation: "Segmentation divides user software logical addresses into variable-length structures called segments." },
            { questionText: "What type of thread context is managed directly by the application layer without kernel interventions?", options: ["Kernel Thread", "User Thread", "Process Thread", "Hardware Thread"], correctOptionIndex: 1, difficulty: "medium", explanation: "User threads run via app runtime engines and do not require OS context switching operations." },

            // Hard (6 Questions)
            { questionText: "Which scheduling algorithm is universally optimal but cannot be fully implemented in practice?", options: ["SJF", "Round Robin", "FCFS", "Optimal Future Scheduling"], correctOptionIndex: 0, difficulty: "hard", explanation: "Shortest Job First (SJF) is theoretically optimal but impossible to implement exactly because future CPU burst times cannot be known dynamically." },
            { questionText: "What describes critical sections in process environments?", options: ["Code segment containing shared resources that must be accessed exclusively", "Memory page sectors containing system drivers", "Disk controllers storing core boot files", "Linux root systems security configurations"], correctOptionIndex: 0, difficulty: "hard", explanation: "Critical sections hold shared memory parameters; concurrent modifications can cause race conditions, requiring mutual exclusion." },
            { questionText: "What specifies the necessary and sufficient conditions for deadlock to occur?", options: ["Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait", "Mutual Exclusion, Priority Inversion, Starvation, Aging", "Semaphore, Mutex, Locking, Barrier Check", "FIFO, LRU, Optimal, Belady Index"], correctOptionIndex: 0, difficulty: "hard", explanation: "The four Coffman conditions must hold simultaneously for a deadlock to exist." },
            { questionText: "What sorting technique is used for Disk I/O scheduling to minimize head movements?", options: ["FCFS, SCAN, C-SCAN, LOOK", "FIFO, LRU, Optimal, Belady", "Round Robin, SJF, SRTF", "Index, Chained, Indexed-Sequential Storage"], correctOptionIndex: 0, difficulty: "hard", explanation: "Disk scheduling algorithms (like SCAN and C-SCAN) handle cylinder seek optimizations." },
            { questionText: "What is a translation lookaside buffer (TLB)?", options: ["High-speed cache used by memory management unit to store page tables translations", "Disk space allocated for swapped memory", "Vector register set in processing units", "Compiler routing database"], correctOptionIndex: 0, difficulty: "hard", explanation: "The TLB is a dedicated hardware cache containing recent virtual-to-physical address mappings." },
            { questionText: "What condition does priority inversion describe under concurrent programming?", options: ["Low priority thread locks resource needed by high priority thread, while medium priority thread preempts low, delaying high", "Priority order of all processes in queue is inverted", "High priority process finishes before scheduler runs", "Scheduler runs in FIFO"], correctOptionIndex: 0, difficulty: "hard", explanation: "Priority inversion occurs when scheduling hierarchies are disrupted by shared locked resources." }
        ]
    },
    {
        title: "Computer Networks (CN)",
        description: "Assessment on OSI reference layers, TCP/IP handshake protocols, routing, subnet configs, and web socket layers.",
        category: "networks",
        difficulty: "general",
        duration: 20,
        questions: [
            // Easy (7 Questions)
            { questionText: "Which layer of the OSI model handles data encrypting and format compression?", options: ["Session Layer", "Application Layer", "Presentation Layer", "Transport Layer"], correctOptionIndex: 2, difficulty: "easy", explanation: "The Presentation Layer translates and formats data, handling compression and encryption." },
            { questionText: "What protocol is used to map dynamic IP addresses to physical MAC keys?", options: ["DHCP", "ARP", "DNS", "ICMP"], correctOptionIndex: 1, difficulty: "easy", explanation: "Address Resolution Protocol (ARP) translates a logical IP address to a physical MAC address." },
            { questionText: "Which OSI level routes packets across intermediate network nodes?", options: ["Data Link Layer", "Physical Layer", "Network Layer", "Transport Layer"], correctOptionIndex: 2, difficulty: "easy", explanation: "The Network Layer manages logical addressing and packet routing." },
            { questionText: "What is the standard IPv4 loopback address?", options: ["192.168.0.1", "127.0.0.1", "10.0.0.1", "255.255.255.255"], correctOptionIndex: 1, difficulty: "easy", explanation: "The IP 127.0.0.1 points directly back to the localhost socket." },
            { questionText: "Which protocol is connection-oriented and reliable?", options: ["UDP", "IP", "TCP", "ICMP"], correctOptionIndex: 2, difficulty: "easy", explanation: "TCP uses handshakes, ACKs, and retransmissions to guarantee packet delivery." },
            { questionText: "What is the size of an IPv6 address in bits?", options: ["32 bits", "64 bits", "128 bits", "256 bits"], correctOptionIndex: 2, difficulty: "easy", explanation: "IPv6 addresses are 128 bits long, written as hexadecimal segments." },
            { questionText: "Which network device operates strictly at the physical layer?", options: ["Switch", "Router", "Hub", "Gateway"], correctOptionIndex: 2, difficulty: "easy", explanation: "Passive hubs amplify and broadcast electrical signals without logical addressing." },

            // Medium (7 Questions)
            { questionText: "What type of DNS record maps hostnames to IPv4 target addresses?", options: ["CNAME Record", "MX Record", "A Record", "AAAA Record"], correctOptionIndex: 2, difficulty: "medium", explanation: "An 'A' Record defines the hostname-to-IPv4 mapping, whereas 'AAAA' defines IPv6 mappings." },
            { questionText: "What subnet range is represented by a /26 CIDR suffix?", options: ["255.255.255.0", "255.255.255.128", "255.255.255.192", "255.255.255.224"], correctOptionIndex: 2, difficulty: "medium", explanation: "A /26 subnet means 26 mask bits are set, leaving 6 host bits, yielding mask 255.255.255.192." },
            { questionText: "In TCP congestion control, what step follows slow start after threshold value is reached?", options: ["Congestion Avoidance", "Fast Recovery", "AIMD Multipliers", "Timeout resets"], correctOptionIndex: 0, difficulty: "medium", explanation: "Once Slow Start reaches ssthresh, it transitions to Congestion Avoidance to grow window sizes linearly." },
            { questionText: "Which routing protocol utilizes Dijkstra's shortest path algorithms?", options: ["RIP", "OSPF", "BGP", "EIGRP"], correctOptionIndex: 1, difficulty: "medium", explanation: "Open Shortest Path First (OSPF) uses Link State databases and Dijkstra's algorithm." },
            { questionText: "Which TCP header flag is used during the handshake to initiate a connection?", options: ["SYN", "ACK", "FIN", "RST"], correctOptionIndex: 0, difficulty: "medium", explanation: "SYN (Synchronize) packets establish initial sequence synchronization targets." },
            { questionText: "What describes the Sliding Window protocol?", options: ["A flow control mechanism allowing multiple packets to be dispatched before receiving ACKs", "A sliding graphics container on client screens", "Routing packet selectors", "Network hub collision check algorithms"], correctOptionIndex: 0, difficulty: "medium", explanation: "Sliding window sizing prevents sender overload by defining max in-flight unacknowledged packets." },
            { questionText: "Which layer handles socket control loops using Socket.IO?", options: ["Transport Layer", "Application Layer", "Network Layer", "Physical Layer"], correctOptionIndex: 1, difficulty: "medium", explanation: "Websockets run on top of Transport protocols, operating at the Application Layer." },

            // Hard (6 Questions)
            { questionText: "What prevents dynamic loop routing in Data Link layer topologies?", options: ["STP (Spanning Tree Protocol)", "OSPF Dynamic routing", "IP Subnet divisions", "CSMA/CD protocol"], correctOptionIndex: 0, difficulty: "hard", explanation: "STP disables redundant bridge paths to avoid link broadcast loops." },
            { questionText: "What algorithm does CSMA/CD use to handle ethernet channel collisions?", options: ["Binary Exponential Backoff", "Sliding window adjustments", "Packet fragment checks", "CRC checksum computations"], correctOptionIndex: 0, difficulty: "hard", explanation: "Exponential Backoff doubles delay intervals randomly on collision to clear channel contention." },
            { questionText: "Which protocol operates the routing connections between Autonomous Systems globally?", options: ["OSPF", "RIP", "BGP (Border Gateway Protocol)", "EIGRP"], correctOptionIndex: 2, difficulty: "hard", explanation: "BGP is the standard path-vector protocol used to route traffic across the internet." },
            { questionText: "What dynamic IP address ranges are reserved private subnets?", options: ["10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16", "224.0.0.0/4 multicasts", "169.254.0.0/16 Link local", "100.64.0.0/10 carrier subnets"], correctOptionIndex: 0, difficulty: "hard", explanation: "These blocks are designated private zones by RFC 1918." },
            { questionText: "In a /27 subnet mask configuration, what is the maximum number of usable hosts?", options: ["32 hosts", "30 hosts", "64 hosts", "62 hosts"], correctOptionIndex: 1, difficulty: "hard", explanation: "Total range is 32 (2^5). Subtracting network boundary and broadcast address leaves 30 usable host IPs." },
            { questionText: "What distinguishes selective repeat ARQ from go-back-N ARQ?", options: ["Selective Repeat buffers out-of-order packets and retransmits only individual failed frames", "Selective Repeat discards all packets after error", "Go-back-N retransmits only one frame", "Selective repeat has zero window sizes"], correctOptionIndex: 0, difficulty: "hard", explanation: "Selective Repeat uses individual timers to retransmit only dropped packets, avoiding bulk retransmissions." }
        ]
    },
    {
        title: "Object-Oriented Programming (OOP)",
        description: "Assessment on core pillars of OOP (Inheritance, Polymorphism, Abstraction, Encapsulation), static/dynamic bindings, and class design.",
        category: "oop",
        difficulty: "general",
        duration: 20,
        questions: [
            // Easy (7 Questions)
            { questionText: "Which pillar of OOP binds codebase variables and methods into a single class container?", options: ["Inheritance", "Polymorphism", "Abstraction", "Encapsulation"], correctOptionIndex: 3, difficulty: "easy", explanation: "Encapsulation keeps data safe within private class attributes, exposing them via public methods." },
            { questionText: "What concept describes creating a subclass from a parent base class?", options: ["Encapsulation", "Polymorphism", "Inheritance", "Instantiation"], correctOptionIndex: 2, difficulty: "easy", explanation: "Inheritance enables a derived class to reuse properties and methods of a base class." },
            { questionText: "Which keyword in Java or C# is used to access parent class constructor definitions?", options: ["super", "this", "parent", "base"], correctOptionIndex: 0, difficulty: "easy", explanation: "The 'super' statement calls method and constructor declarations in parent classes." },
            { questionText: "What constructor automatically runs when an object is instantiated?", options: ["Default Constructor", "Copy Constructor", "Destructor", "Static constructor"], correctOptionIndex: 0, difficulty: "easy", explanation: "The default constructor initializes class structures with default parameters when instantiated." },
            { questionText: "Which specifier hides variables from external entities but shares them with subclasses?", options: ["private", "public", "protected", "internal"], correctOptionIndex: 2, difficulty: "easy", explanation: "Protected fields are accessible only to declaring classes and derived classes." },
            { questionText: "What represents a concrete instance of a class?", options: ["Interface", "Object", "Package", "Method"], correctOptionIndex: 1, difficulty: "easy", explanation: "An object is a runtime instance created from class definitions." },
            { questionText: "What OOP concept allows one interface to represent different actions?", options: ["Polymorphism", "Abstraction", "Inheritance", "Encapsulation"], correctOptionIndex: 0, difficulty: "easy", explanation: "Polymorphism (meaning 'many forms') allows methods to act differently based on parameters or runtime bindings." },

            // Medium (7 Questions)
            { questionText: "What distinguishes method overloading from overloading operators?", options: ["Overloading uses compile-time parameters; operators redefine operation behaviors on objects", "Method overloading is dynamic; operators are compile-time binding only", "Operators cannot be overloaded in any language", "They represent the exact same compiler mechanism"], correctOptionIndex: 0, difficulty: "medium", explanation: "Method overloading uses arguments to bind methods, and operator overloading adapts standard operations (e.g. +) to custom objects." },
            { questionText: "What is an abstract class?", options: ["A class containing at least one abstract method that cannot be instantiated directly", "A class with all code fields public", "A variable database index", "An interface containing only static constants"], correctOptionIndex: 0, difficulty: "medium", explanation: "Abstract classes define structural interfaces for inheritance and cannot be directly instantiated." },
            { questionText: "What type of polymorphism is implemented via virtual method tables at runtime?", options: ["Compile-time Polymorphism", "Run-time Polymorphism", "Ad-hoc polymorphism", "Parametric overrides"], correctOptionIndex: 1, difficulty: "medium", explanation: "Dynamic runtime polymorphism uses VTables to determine virtual override bindings on child instances." },
            { questionText: "What relation is represented by Composition in class designs?", options: ["Is-a relation", "Has-a relation", "Uses-a relation", "Binds-a relation"], correctOptionIndex: 1, difficulty: "medium", explanation: "Composition is a strong 'Has-a' association where container objects manage the lifecycles of nested objects." },
            { questionText: "Which OOP concept details a template contract without any body implementations?", options: ["Interface", "Abstract Class", "Virtual Method", "Overload Method"], correctOptionIndex: 0, difficulty: "medium", explanation: "An Interface defines a pure signature skeleton that implementing classes must define." },
            { questionText: "What is the difference between composition and aggregation?", options: ["Composition represents strict ownership; nested instances die with container. Aggregation lifecycle is independent", "Aggregation represents inheritance; composition does not", "Composition is a compile-time link", "They are identical in design patterns"], correctOptionIndex: 0, difficulty: "medium", explanation: "Composition defines tight coupling (e.g. Engine inside Car), whereas Aggregation is loose pairing (e.g. Teacher in School)." },
            { questionText: "Which specifier is the default in C++ classes if none is provided?", options: ["public", "private", "protected", "friend"], correctOptionIndex: 1, difficulty: "medium", explanation: "In C++, members of class block structures default to private access, unlike structs which default to public." },

            // Hard (6 Questions)
            { questionText: "What problem arises from diamond inheritance patterns?", options: ["Ambiguity during multiple inheritance where child inherits same field twice from split ancestors", "Compilation halts due to infinite pointer referencing", "Lack of memory partition controls", "Object destructors fail to execute"], correctOptionIndex: 0, difficulty: "hard", explanation: "Diamond layouts cause ambiguity when calls are dispatched to ancestral methods. Virtual inheritance fixes this." },
            { questionText: "What is virtual inheritance used for in C++?", options: ["Avoiding duplicate grandparent objects within diamond inheritance trees", "Speeding up pointer evaluations", "Making all methods public", "Generating mock interfaces"], correctOptionIndex: 0, difficulty: "hard", explanation: "In C++, virtual inheritance guarantees child paths merge ancestral records into a single base instance." },
            { questionText: "What is the Liskov Substitution Principle (LSP) in SOLID design?", options: ["Subtypes must be substitutable for their base types without altering validity", "Classes should have single responsibilities", "Interfaces must be segregated", "High modules should not depend on low modules"], correctOptionIndex: 0, difficulty: "hard", explanation: "LSP guarantees that subclasses override parent methods without breaking program contracts." },
            { questionText: "What describes early binding?", options: ["Compile-time resolution of function calls based on static signatures", "Runtime resolution of overrides using pointer vtables", "Boot time load operations", "Initialization of constants"], correctOptionIndex: 0, difficulty: "hard", explanation: "Early binding binds code triggers during compilation step, boosting processing speed." },
            { questionText: "What is object slicing in C++?", options: ["Assigning a derived class object to a base class variable, cutting off derived attributes", "Splitting an array of classes", "Reclaiming memory of deleted variables", "Parsing a class to string structures"], correctOptionIndex: 0, difficulty: "hard", explanation: "Object slicing occurs when subclass values are copied into base structures, slicing off derived attributes." },
            { questionText: "What character writes destructors in C++?", options: ["~ (Tilde)", "* (Asterisk)", "& (Ampersand)", "# (Hash)"], correctOptionIndex: 0, difficulty: "hard", explanation: "C++ destructors are declared using a tilde (~) prefixing the class name." }
        ]
    }
];

module.exports = coreSubjectTests;
