/**
 * CAMPUSBRIDGE — ENTERPRISE PERMISSIONS & RBAC REGISTRY
 * Centralized, immutable permission constants and role-permission matrices.
 * Preserves 100% backward compatibility for existing roles ('admin', 'faculty', 'hod', 'recruiter', 'student').
 */

// 1. GRANULAR PERMISSION CONSTANTS
const PERMISSIONS = Object.freeze({
  // Campus & Multi-Tenant Management
  CAMPUS_VIEW: 'CAMPUS_VIEW',
  CAMPUS_CREATE: 'CAMPUS_CREATE',
  CAMPUS_UPDATE: 'CAMPUS_UPDATE',
  CAMPUS_DELETE: 'CAMPUS_DELETE',

  // Department & Branch Management
  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE: 'DEPARTMENT_DELETE',

  // User & Identity Management
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_LOCK: 'USER_LOCK',
  USER_UNLOCK: 'USER_UNLOCK',
  STAFF_MANAGE: 'STAFF_MANAGE',
  SCOPE_ASSIGN: 'SCOPE_ASSIGN',

  // Student Operations
  STUDENT_VIEW: 'STUDENT_VIEW',
  STUDENT_UPDATE: 'STUDENT_UPDATE',
  STUDENT_DELETE: 'STUDENT_DELETE',
  STUDENT_IMPORT: 'STUDENT_IMPORT',
  STUDENT_EXPORT: 'STUDENT_EXPORT',
  STUDENT_PROGRESS_VIEW: 'STUDENT_PROGRESS_VIEW',

  // Academic Management
  ACADEMIC_VIEW: 'ACADEMIC_VIEW',
  ACADEMIC_UPDATE: 'ACADEMIC_UPDATE',
  SUBJECT_VIEW: 'SUBJECT_VIEW',
  SUBJECT_CREATE: 'SUBJECT_CREATE',
  SUBJECT_UPDATE: 'SUBJECT_UPDATE',
  SUBJECT_DELETE: 'SUBJECT_DELETE',
  NOTES_UPLOAD: 'NOTES_UPLOAD',
  NOTES_DELETE: 'NOTES_DELETE',

  // Marks & Grading
  MARKS_VIEW: 'MARKS_VIEW',
  MARKS_WRITE: 'MARKS_WRITE',
  MARKS_BULK_IMPORT: 'MARKS_BULK_IMPORT',
  MARKS_PUBLISH: 'MARKS_PUBLISH',

  // Attendance
  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_WRITE: 'ATTENDANCE_WRITE',

  // Projects & Studio
  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',
  PROJECT_REVIEW: 'PROJECT_REVIEW',
  PROJECT_GRADE: 'PROJECT_GRADE',
  PROJECT_APPROVE: 'PROJECT_APPROVE',

  // Coding & Contests
  CODING_VIEW: 'CODING_VIEW',
  CODING_SUBMIT: 'CODING_SUBMIT',
  CODING_REVIEW: 'CODING_REVIEW',
  CONTEST_MANAGE: 'CONTEST_MANAGE',

  // Labs & Practice
  LAB_VIEW: 'LAB_VIEW',
  LAB_CREATE: 'LAB_CREATE',
  LAB_SUBMIT: 'LAB_SUBMIT',
  LAB_REVIEW: 'LAB_REVIEW',
  LAB_DELETE: 'LAB_DELETE',

  // Assessments & Question Bank
  TEST_VIEW: 'TEST_VIEW',
  TEST_CREATE: 'TEST_CREATE',
  TEST_UPDATE: 'TEST_UPDATE',
  TEST_DELETE: 'TEST_DELETE',
  TEST_ATTEMPT: 'TEST_ATTEMPT',
  QUESTION_MANAGE: 'QUESTION_MANAGE',

  // Company & Recruitment
  COMPANY_VIEW: 'COMPANY_VIEW',
  COMPANY_CREATE: 'COMPANY_CREATE',
  COMPANY_UPDATE: 'COMPANY_UPDATE',
  COMPANY_DELETE: 'COMPANY_DELETE',

  // Placement Drives
  PLACEMENT_DRIVE_VIEW: 'PLACEMENT_DRIVE_VIEW',
  PLACEMENT_DRIVE_CREATE: 'PLACEMENT_DRIVE_CREATE',
  PLACEMENT_DRIVE_UPDATE: 'PLACEMENT_DRIVE_UPDATE',
  PLACEMENT_DRIVE_DELETE: 'PLACEMENT_DRIVE_DELETE',
  PLACEMENT_DRIVE_PUBLISH: 'PLACEMENT_DRIVE_PUBLISH',
  PLACEMENT_DRIVE_CANCEL: 'PLACEMENT_DRIVE_CANCEL',

  // Candidate Applications
  APPLICATION_VIEW: 'APPLICATION_VIEW',
  APPLICATION_APPLY: 'APPLICATION_APPLY',
  APPLICATION_UPDATE: 'APPLICATION_UPDATE',
  APPLICATION_SHORTLIST: 'APPLICATION_SHORTLIST',
  APPLICATION_STATUS_UPDATE: 'APPLICATION_STATUS_UPDATE',

  // Interviews & Schedules
  INTERVIEW_VIEW: 'INTERVIEW_VIEW',
  INTERVIEW_SCHEDULE: 'INTERVIEW_SCHEDULE',
  INTERVIEW_UPDATE: 'INTERVIEW_UPDATE',
  INTERVIEW_CONDUCT: 'INTERVIEW_CONDUCT',

  // Placement Results & Offers
  PLACEMENT_RESULT_VIEW: 'PLACEMENT_RESULT_VIEW',
  PLACEMENT_RESULT_UPDATE: 'PLACEMENT_RESULT_UPDATE',
  OFFER_MANAGE: 'OFFER_MANAGE',

  // Reports & Analytics
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_EXPORT: 'REPORT_EXPORT',
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',

  // Audit & Security
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  AUDIT_LOG_DELETE: 'AUDIT_LOG_DELETE',
  SECURITY_MANAGE: 'SECURITY_MANAGE',

  // AI & System Configuration
  AI_USE: 'AI_USE',
  AI_CONFIGURE: 'AI_CONFIGURE',
  SYSTEM_CONFIGURE: 'SYSTEM_CONFIGURE'
});

// All permissions as a flat list
const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));

// 2. ROLE DEFINITIONS
const ROLES = Object.freeze({
  SUPER_ADMIN: 'super_admin',
  CAMPUS_ADMIN: 'campus_admin',
  ADMINISTRATOR: 'administrator',
  HOD: 'hod',
  FACULTY: 'faculty',
  PLACEMENT_OFFICER: 'placement_officer',
  RECRUITER: 'recruiter',
  STUDENT: 'student',
  AUDITOR: 'auditor',
  DIRECTOR: 'director',
  PRINCIPAL: 'principal',

  // Legacy role identifier preserved for complete backward compatibility
  ADMIN: 'admin'
});

// 3. ROLE-TO-PERMISSION MAPPINGS
const ROLE_PERMISSIONS = Object.freeze({
  // SUPER ADMIN: Unrestricted Platform-Wide Privileges
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  // DIRECTOR: Institutional Executive Leadership & Governance (Read/Audit/Analytics/Oversight — strictly non-destructive)
  [ROLES.DIRECTOR]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_APPROVE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.CONTEST_MANAGE,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.QUESTION_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // PRINCIPAL: Institutional Academic Leadership & Curriculum Oversight (Non-destructive)
  [ROLES.PRINCIPAL]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ACADEMIC_UPDATE,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SUBJECT_CREATE,
    PERMISSIONS.SUBJECT_UPDATE,
    PERMISSIONS.NOTES_UPLOAD,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_REVIEW,
    PERMISSIONS.PROJECT_GRADE,
    PERMISSIONS.PROJECT_APPROVE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.CONTEST_MANAGE,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_REVIEW,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.QUESTION_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // LEGACY ADMIN: Backward-compatible alias matching full Administrative privileges
  [ROLES.ADMIN]: ALL_PERMISSIONS,

  // CAMPUS ADMIN: Full operational access restricted to their assigned Campus
  [ROLES.CAMPUS_ADMIN]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.CAMPUS_UPDATE,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_LOCK,
    PERMISSIONS.USER_UNLOCK,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.SCOPE_ASSIGN,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.STUDENT_IMPORT,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ACADEMIC_UPDATE,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SUBJECT_CREATE,
    PERMISSIONS.SUBJECT_UPDATE,
    PERMISSIONS.SUBJECT_DELETE,
    PERMISSIONS.NOTES_UPLOAD,
    PERMISSIONS.NOTES_DELETE,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.MARKS_WRITE,
    PERMISSIONS.MARKS_BULK_IMPORT,
    PERMISSIONS.MARKS_PUBLISH,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_REVIEW,
    PERMISSIONS.PROJECT_GRADE,
    PERMISSIONS.PROJECT_APPROVE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.CONTEST_MANAGE,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_CREATE,
    PERMISSIONS.LAB_REVIEW,
    PERMISSIONS.LAB_DELETE,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,
    PERMISSIONS.TEST_DELETE,
    PERMISSIONS.QUESTION_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_CREATE,
    PERMISSIONS.PLACEMENT_DRIVE_UPDATE,
    PERMISSIONS.PLACEMENT_DRIVE_PUBLISH,
    PERMISSIONS.PLACEMENT_DRIVE_CANCEL,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.APPLICATION_SHORTLIST,
    PERMISSIONS.APPLICATION_STATUS_UPDATE,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.INTERVIEW_SCHEDULE,
    PERMISSIONS.INTERVIEW_UPDATE,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_UPDATE,
    PERMISSIONS.OFFER_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // ADMINISTRATOR: Permitted Campus Operational Management
  [ROLES.ADMINISTRATOR]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_LOCK,
    PERMISSIONS.USER_UNLOCK,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.SCOPE_ASSIGN,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.STUDENT_IMPORT,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ACADEMIC_UPDATE,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SUBJECT_CREATE,
    PERMISSIONS.SUBJECT_UPDATE,
    PERMISSIONS.NOTES_UPLOAD,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.MARKS_WRITE,
    PERMISSIONS.MARKS_BULK_IMPORT,
    PERMISSIONS.MARKS_PUBLISH,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_REVIEW,
    PERMISSIONS.PROJECT_GRADE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.CONTEST_MANAGE,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_CREATE,
    PERMISSIONS.LAB_REVIEW,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,
    PERMISSIONS.TEST_DELETE,
    PERMISSIONS.QUESTION_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_CREATE,
    PERMISSIONS.PLACEMENT_DRIVE_UPDATE,
    PERMISSIONS.PLACEMENT_DRIVE_CANCEL,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.APPLICATION_SHORTLIST,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.INTERVIEW_SCHEDULE,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // HOD: Department Scope Access
  [ROLES.HOD]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.STUDENT_EXPORT,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.SUBJECT_CREATE,
    PERMISSIONS.SUBJECT_UPDATE,
    PERMISSIONS.SUBJECT_DELETE,
    PERMISSIONS.NOTES_UPLOAD,
    PERMISSIONS.NOTES_DELETE,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.MARKS_WRITE,
    PERMISSIONS.MARKS_BULK_IMPORT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_REVIEW,
    PERMISSIONS.PROJECT_GRADE,
    PERMISSIONS.PROJECT_APPROVE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_CREATE,
    PERMISSIONS.LAB_REVIEW,
    PERMISSIONS.LAB_DELETE,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,
    PERMISSIONS.QUESTION_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // FACULTY: Assignment-Based Scope Access
  [ROLES.FACULTY]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.NOTES_UPLOAD,
    PERMISSIONS.NOTES_DELETE,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.MARKS_WRITE,
    PERMISSIONS.MARKS_BULK_IMPORT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_REVIEW,
    PERMISSIONS.PROJECT_GRADE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_CREATE,
    PERMISSIONS.LAB_REVIEW,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,
    PERMISSIONS.QUESTION_MANAGE,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // PLACEMENT OFFICER: Campus Placement Operations
  [ROLES.PLACEMENT_OFFICER]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.STUDENT_PROGRESS_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_CREATE,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.COMPANY_DELETE,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_CREATE,
    PERMISSIONS.PLACEMENT_DRIVE_UPDATE,
    PERMISSIONS.PLACEMENT_DRIVE_DELETE,
    PERMISSIONS.PLACEMENT_DRIVE_PUBLISH,
    PERMISSIONS.PLACEMENT_DRIVE_CANCEL,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.APPLICATION_SHORTLIST,
    PERMISSIONS.APPLICATION_STATUS_UPDATE,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.INTERVIEW_SCHEDULE,
    PERMISSIONS.INTERVIEW_UPDATE,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_UPDATE,
    PERMISSIONS.OFFER_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // RECRUITER: Own Company & Drive Applicants Access Only
  [ROLES.RECRUITER]: Object.freeze([
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_CREATE,
    PERMISSIONS.PLACEMENT_DRIVE_UPDATE,
    PERMISSIONS.PLACEMENT_DRIVE_CANCEL,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.APPLICATION_SHORTLIST,
    PERMISSIONS.APPLICATION_STATUS_UPDATE,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.INTERVIEW_SCHEDULE,
    PERMISSIONS.INTERVIEW_UPDATE,
    PERMISSIONS.INTERVIEW_CONDUCT,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_UPDATE
  ]),

  // STUDENT: Own Data & Public Campus Resources
  [ROLES.STUDENT]: Object.freeze([
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.SUBJECT_VIEW,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.CODING_VIEW,
    PERMISSIONS.CODING_SUBMIT,
    PERMISSIONS.LAB_VIEW,
    PERMISSIONS.LAB_SUBMIT,
    PERMISSIONS.TEST_VIEW,
    PERMISSIONS.TEST_ATTEMPT,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.APPLICATION_APPLY,
    PERMISSIONS.INTERVIEW_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.AI_USE
  ]),

  // AUDITOR: Strictly Read-Only View of Logs and Activity
  [ROLES.AUDITOR]: Object.freeze([
    PERMISSIONS.CAMPUS_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.MARKS_VIEW,
    PERMISSIONS.PLACEMENT_DRIVE_VIEW,
    PERMISSIONS.APPLICATION_VIEW,
    PERMISSIONS.PLACEMENT_RESULT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW
  ])
});

// 4. HELPER UTILITIES

/**
 * Normalize role strings for consistency (handles casing and legacy aliases)
 * @param {string} role
 * @returns {string}
 */
const normalizeRole = (role) => {
  if (!role || typeof role !== 'string') return ROLES.STUDENT;
  const clean = role.trim().toLowerCase();
  if (clean === 'admin') return ROLES.ADMIN;
  return clean;
};

/**
 * Retrieve all permissions for a given role plus any optional custom permissions
 * @param {string} role
 * @param {string[]} [customPermissions=[]]
 * @returns {Set<string>}
 */
const getRolePermissions = (role, customPermissions = []) => {
  const normalized = normalizeRole(role);
  const basePermissions = ROLE_PERMISSIONS[normalized] || ROLE_PERMISSIONS[ROLES.STUDENT] || [];
  const permissionSet = new Set(basePermissions);

  if (Array.isArray(customPermissions)) {
    customPermissions.forEach((perm) => {
      if (typeof perm === 'string' && PERMISSIONS[perm]) {
        permissionSet.add(perm);
      }
    });
  }

  return permissionSet;
};

/**
 * Check if a role possesses a specific permission
 * @param {string} role
 * @param {string} permission
 * @param {string[]} [customPermissions=[]]
 * @returns {boolean}
 */
const hasRolePermission = (role, permission, customPermissions = []) => {
  if (!permission) return false;
  const permissions = getRolePermissions(role, customPermissions);
  return permissions.has(permission);
};

module.exports = {
  PERMISSIONS,
  ALL_PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
  normalizeRole,
  getRolePermissions,
  hasRolePermission
};
